"""
Generate the Gohil's Group mark as clean SVG from measured geometry.

Every constant below was measured off client-assets/WhatsApp Image 2026-08-24
at 8.29.27 PM.jpeg (the largest instance of the logo we have), not eyeballed:

  ring centre    (160.30, 163.55) source px, least-squares circle fit
  outer radius   89.5
  inner radius   68.0   -> stroke width 21.5
  orange arc     45deg to 225deg   (exactly 180deg)
  pale arc       225deg to 270deg  (45deg)
  the G          270deg to 360deg  (90deg) plus a crossbar on the
                 horizontal diameter, left edge on the vertical centre
  gap            0deg to 45deg, which is where "Gohil's" sits

Normalised to a 200x200 viewBox, centre (100,100), outer radius 90.

Run:  python scripts/build-mark.py
"""

import math
import os

CX = CY = 100.0
R_OUT = 90.0
STROKE = 21.5
R_IN = R_OUT - STROKE  # 68.5
HALF_BAR = STROKE / 2  # the crossbar sits on the horizontal diameter

ORANGE = "#E8500C"
PALE = "#D3D5D7"
GRAPHITE = "#646668"

OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "public", "brand")


def pt(deg: float, r: float) -> tuple[float, float]:
    """Polar to SVG. Angles are maths convention (0 = east, CCW positive)."""
    th = math.radians(deg)
    return (CX + r * math.cos(th), CY - r * math.sin(th))


def f(v: float) -> str:
    return f"{v:.3f}".rstrip("0").rstrip(".")


def ring_segment(start_deg: float, end_deg: float) -> str:
    """
    A closed annulus segment with flat radial end caps, exactly how the
    client's own arcs terminate.
    """
    sweep = end_deg - start_deg
    large = 1 if abs(sweep) > 180 else 0
    # Maths-CCW renders as counter-clockwise on screen, which is sweep-flag 0.
    sf_outer, sf_inner = 0, 1
    o1, o2 = pt(start_deg, R_OUT), pt(end_deg, R_OUT)
    i1, i2 = pt(end_deg, R_IN), pt(start_deg, R_IN)
    return (
        f"M{f(o1[0])} {f(o1[1])}"
        f"A{f(R_OUT)} {f(R_OUT)} 0 {large} {sf_outer} {f(o2[0])} {f(o2[1])}"
        f"L{f(i1[0])} {f(i1[1])}"
        f"A{f(R_IN)} {f(R_IN)} 0 {large} {sf_inner} {f(i2[0])} {f(i2[1])}"
        "Z"
    )


def g_path() -> str:
    """
    The G. Outer arc from the crossbar's top edge clockwise round the bottom
    to the vertical centre, up the flat left edge, back along the inner arc,
    then left along the underside of the crossbar.
    """
    bar_top_y = CY - HALF_BAR
    bar_bot_y = CY + HALF_BAR
    # where the crossbar's top and bottom edges meet the two circles
    x_out_top = CX + math.sqrt(R_OUT**2 - HALF_BAR**2)
    x_in_bot = CX + math.sqrt(R_IN**2 - HALF_BAR**2)
    ang_out_top = math.degrees(math.atan2(HALF_BAR, x_out_top - CX))
    bottom_out = (CX, CY + R_OUT)
    bottom_in = (CX, CY + R_IN)
    # outer sweep runs from just above east, clockwise on screen, to due south
    large_out = 1 if (ang_out_top + 90) > 180 else 0
    return (
        f"M{f(CX)} {f(bar_top_y)}"
        f"L{f(x_out_top)} {f(bar_top_y)}"
        f"A{f(R_OUT)} {f(R_OUT)} 0 {large_out} 1 {f(bottom_out[0])} {f(bottom_out[1])}"
        f"L{f(bottom_in[0])} {f(bottom_in[1])}"
        f"A{f(R_IN)} {f(R_IN)} 0 0 0 {f(x_in_bot)} {f(bar_bot_y)}"
        f"L{f(CX)} {f(bar_bot_y)}"
        "Z"
    )


ORANGE_D = ring_segment(45, 225)
PALE_D = ring_segment(225, 270)
G_D = g_path()

FULL = f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200" role="img" aria-label="Gohil's Group">
  <path class="mark-pale" d="{PALE_D}" fill="{PALE}"/>
  <path class="mark-g" d="{G_D}" fill="{GRAPHITE}"/>
  <path class="mark-arc" d="{ORANGE_D}" fill="{ORANGE}"/>
</svg>
"""

# Single colour cut, for the ink and mist reversals and the favicon.
MONO = f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200" role="img" aria-label="Gohil's Group">
  <path d="{PALE_D}" fill="currentColor" opacity="0.35"/>
  <path d="{G_D}" fill="currentColor"/>
  <path d="{ORANGE_D}" fill="currentColor"/>
</svg>
"""

# Stroke-only cut. The load animation draws these three arcs.
OUTLINE = f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200" role="img" aria-label="Gohil's Group">
  <g fill="none" stroke-width="1.5">
    <path class="mark-pale" d="{PALE_D}" stroke="{PALE}"/>
    <path class="mark-g" d="{G_D}" stroke="{GRAPHITE}"/>
    <path class="mark-arc" d="{ORANGE_D}" stroke="{ORANGE}"/>
  </g>
</svg>
"""

TS = f"""/**
 * Path data for the Gohil's Group mark.
 *
 * GENERATED by scripts/build-mark.py. Do not edit by hand.
 * Re-run the script if the geometry changes.
 *
 * One ring, centre fitted by least squares off client-assets image 2.
 * Outer radius {R_OUT}, stroke {STROKE}, on a 200 x 200 viewBox.
 * Orange 45deg to 225deg, pale 225deg to 270deg, the G 270deg to 360deg
 * plus a crossbar on the horizontal diameter, gap 0deg to 45deg.
 */

export const MARK_VIEWBOX = '0 0 200 200'

export const MARK_PATHS = {{
  /** Lower left arc. Nearly invisible on a light ground, which is the point. */
  pale: '{PALE_D}',
  /** The G. Its bowl closes the ring on the right. */
  g: '{G_D}',
  /** The 180 degree orange arc. */
  arc: '{ORANGE_D}',
}} as const

export const MARK_COLOURS = {{
  pale: '{PALE}',
  g: '{GRAPHITE}',
  arc: '{ORANGE}',
}} as const
"""

if __name__ == "__main__":
    os.makedirs(OUT_DIR, exist_ok=True)
    ts_dir = os.path.join(os.path.dirname(__file__), "..", "src", "data")
    os.makedirs(ts_dir, exist_ok=True)
    ts_path = os.path.join(ts_dir, "mark-paths.ts")
    with open(ts_path, "w", encoding="utf-8") as fh:
        fh.write(TS)
    print(f"wrote {os.path.normpath(ts_path)}")
    for name, body in [
        ("g-mark.svg", FULL),
        ("g-mark-mono.svg", MONO),
        ("g-mark-outline.svg", OUTLINE),
    ]:
        path = os.path.join(OUT_DIR, name)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(body)
        print(f"wrote {os.path.normpath(path)}  ({len(body)} bytes)")

    print()
    print(f"  outer radius {R_OUT}  inner {R_IN}  stroke {STROKE}")
    print(f"  orange 45-225   pale 225-270   G 270-360 + crossbar   gap 0-45")
