"""
Generate the Gohil's Group mark as clean SVG from measured geometry.

Every constant below was measured off client-assets/WhatsApp Image 2026-08-24
at 8.29.27 PM.jpeg (the largest instance of the logo we have), not eyeballed:

  ring centre    (160.30, 163.55) source px, least-squares circle fit
  outer radius   89.5
  inner radius   68.0   -> stroke width 21.5
  orange arc     45deg to 225deg   (exactly 180deg)
  pale arc       225deg to 270deg  (45deg)
  the G          270deg to 360deg  (90deg) plus a crossbar on the
                 horizontal diameter, left edge on the vertical centre
  gap            0deg to 45deg, which is where "Gohil's" sits

Normalised to a 200x200 viewBox, centre (100,100), outer radius 90.

Run:  python scripts/build-mark.py
"""

import math
import os

CX = CY = 100.0
R_OUT = 90.0
STROKE = 21.5
R_IN = R_OUT - STROKE  # 68.5
HALF_BAR = STROKE / 2  # the crossbar sits on the horizontal diameter

ORANGE = "#E8500C"
PALE = "#D3D5D7"
GRAPHITE = "#646668"

OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "public", "brand")
APP_DIR = os.path.join(os.path.dirname(__file__), "..", "src", "app")

# Apple renders a touch icon on an opaque tile and composites transparency
# against black, so this one gets the page ground rather than an alpha hole.
MIST = "#EAEBED"


def pt(deg: float, r: float) -> tuple[float, float]:
    """Polar to SVG. Angles are maths convention (0 = east, CCW positive)."""
    th = math.radians(deg)
    return (CX + r * math.cos(th), CY - r * math.sin(th))


def f(v: float) -> str:
    return f"{v:.3f}".rstrip("0").rstrip(".")


def ring_segment(start_deg: float, end_deg: float) -> str:
    """
    A closed annulus segment with flat radial end caps, exactly how the
    client's own arcs terminate.
    """
    sweep = end_deg - start_deg
    large = 1 if abs(sweep) > 180 else 0
    # Maths-CCW renders as counter-clockwise on screen, which is sweep-flag 0.
    sf_outer, sf_inner = 0, 1
    o1, o2 = pt(start_deg, R_OUT), pt(end_deg, R_OUT)
    i1, i2 = pt(end_deg, R_IN), pt(start_deg, R_IN)
    return (
        f"M{f(o1[0])} {f(o1[1])}"
        f"A{f(R_OUT)} {f(R_OUT)} 0 {large} {sf_outer} {f(o2[0])} {f(o2[1])}"
        f"L{f(i1[0])} {f(i1[1])}"
        f"A{f(R_IN)} {f(R_IN)} 0 {large} {sf_inner} {f(i2[0])} {f(i2[1])}"
        "Z"
    )


def g_path() -> str:
    """
    The G. Outer arc from the crossbar's top edge clockwise round the bottom
    to the vertical centre, up the flat left edge, back along the inner arc,
    then left along the underside of the crossbar.
    """
    bar_top_y = CY - HALF_BAR
    bar_bot_y = CY + HALF_BAR
    # where the crossbar's top and bottom edges meet the two circles
    x_out_top = CX + math.sqrt(R_OUT**2 - HALF_BAR**2)
    x_in_bot = CX + math.sqrt(R_IN**2 - HALF_BAR**2)
    ang_out_top = math.degrees(math.atan2(HALF_BAR, x_out_top - CX))
    bottom_out = (CX, CY + R_OUT)
    bottom_in = (CX, CY + R_IN)
    # outer sweep runs from just above east, clockwise on screen, to due south
    large_out = 1 if (ang_out_top + 90) > 180 else 0
    return (
        f"M{f(CX)} {f(bar_top_y)}"
        f"L{f(x_out_top)} {f(bar_top_y)}"
        f"A{f(R_OUT)} {f(R_OUT)} 0 {large_out} 1 {f(bottom_out[0])} {f(bottom_out[1])}"
        f"L{f(bottom_in[0])} {f(bottom_in[1])}"
        f"A{f(R_IN)} {f(R_IN)} 0 0 0 {f(x_in_bot)} {f(bar_bot_y)}"
        f"L{f(CX)} {f(bar_bot_y)}"
        "Z"
    )


ORANGE_D = ring_segment(45, 225)
PALE_D = ring_segment(225, 270)
G_D = g_path()

FULL = f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200" role="img" aria-label="Gohil's Group">
  <path class="mark-pale" d="{PALE_D}" fill="{PALE}"/>
  <path class="mark-g" d="{G_D}" fill="{GRAPHITE}"/>
  <path class="mark-arc" d="{ORANGE_D}" fill="{ORANGE}"/>
</svg>
"""

# Single colour cut, for the ink and mist reversals and the favicon.
MONO = f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200" role="img" aria-label="Gohil's Group">
  <path d="{PALE_D}" fill="currentColor" opacity="0.35"/>
  <path d="{G_D}" fill="currentColor"/>
  <path d="{ORANGE_D}" fill="currentColor"/>
</svg>
"""

# Stroke-only cut. The load animation draws these three arcs.
OUTLINE = f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200" role="img" aria-label="Gohil's Group">
  <g fill="none" stroke-width="1.5">
    <path class="mark-pale" d="{PALE_D}" stroke="{PALE}"/>
    <path class="mark-g" d="{G_D}" stroke="{GRAPHITE}"/>
    <path class="mark-arc" d="{ORANGE_D}" stroke="{ORANGE}"/>
  </g>
</svg>
"""

TS = f"""/**
 * Path data for the Gohil's Group mark.
 *
 * GENERATED by scripts/build-mark.py. Do not edit by hand.
 * Re-run the script if the geometry changes.
 *
 * One ring, centre fitted by least squares off client-assets image 2.
 * Outer radius {R_OUT}, stroke {STROKE}, on a 200 x 200 viewBox.
 * Orange 45deg to 225deg, pale 225deg to 270deg, the G 270deg to 360deg
 * plus a crossbar on the horizontal diameter, gap 0deg to 45deg.
 */

export const MARK_VIEWBOX = '0 0 200 200'

export const MARK_PATHS = {{
  /** Lower left arc. Nearly invisible on a light ground, which is the point. */
  pale: '{PALE_D}',
  /** The G. Its bowl closes the ring on the right. */
  g: '{G_D}',
  /** The 180 degree orange arc. */
  arc: '{ORANGE_D}',
}} as const

export const MARK_COLOURS = {{
  pale: '{PALE}',
  g: '{GRAPHITE}',
  arc: '{ORANGE}',
}} as const
"""

def render_mark(px: int, background: str | None = None):
    """
    The mark as a raster, drawn from the same constants as the SVG above rather
    than by rasterising the SVG. No rasteriser is a dependency of this project,
    and re-deriving the geometry here keeps the two cuts honest: if the ring
    ever moves, both move together or neither does.

    Supersampled 8x and reduced with Lanczos, because the edges that matter are
    the flat radial end caps and a 16px icon shows every stair on them.

    PIL measures angles clockwise from east; the constants above are maths
    convention, counter-clockwise from east. The two are mirrored in y, so each
    maths span [a, b] becomes the PIL span [-b, -a]:

        orange  maths  45 to 225  ->  PIL 135 to 315
        pale    maths 225 to 270  ->  PIL  90 to 135
        the G   maths 270 to 360  ->  PIL   0 to  90
    """
    from PIL import Image, ImageChops, ImageDraw

    ss = 8
    size = px * ss
    # The ring is drawn at 92% of the tile, which is the usual favicon breathing
    # room. Below that it reads as a dot on a browser tab.
    scale = (size * 0.92) / (R_OUT * 2)
    cx = cy = size / 2

    def box(r: float):
        rr = r * scale
        return [cx - rr, cy - rr, cx + rr, cy + rr]

    def annulus(start: float, end: float):
        """One ring segment as an 8 bit mask, with the bore punched out."""
        m = Image.new("L", (size, size), 0)
        d = ImageDraw.Draw(m)
        d.pieslice(box(R_OUT), start, end, fill=255)
        d.ellipse(box(R_IN), fill=0)
        return m

    pale_m = annulus(90, 135)
    arc_m = annulus(135, 315)

    # The G is the quarter annulus plus the crossbar. The bar runs from the
    # centre out to the outer circle, and its corners land exactly on that
    # circle at y = cy +/- HALF_BAR, so it needs no clipping. It deliberately
    # crosses the bore: that crossing is what makes the ring read as a G.
    g_m = annulus(0, 90)
    bar = Image.new("L", (size, size), 0)
    x_out_top = CX + math.sqrt(R_OUT**2 - HALF_BAR**2)
    ImageDraw.Draw(bar).rectangle(
        [cx, cy - HALF_BAR * scale, cx + (x_out_top - CX) * scale, cy + HALF_BAR * scale],
        fill=255,
    )
    g_m = ImageChops.lighter(g_m, bar)

    img = Image.new("RGBA", (size, size), (0, 0, 0, 0) if background is None else background)
    # Same paint order as the SVG: pale, then the G, then the orange arc on top.
    for colour, mask in ((PALE, pale_m), (GRAPHITE, g_m), (ORANGE, arc_m)):
        img.paste(colour, mask=mask)

    return img.resize((px, px), Image.LANCZOS)


def build_icons() -> None:
    """favicon.ico, icon.svg and apple-icon.png, all from the geometry above."""
    try:
        from PIL import Image  # noqa: F401
    except ImportError:
        print("  ! Pillow not installed, skipping the raster icons")
        return

    os.makedirs(APP_DIR, exist_ok=True)

    # Next.js App Router picks these up by filename. icon.svg is what every
    # current browser actually uses; the .ico is the fallback for the ones
    # that do not take an SVG.
    svg_path = os.path.join(APP_DIR, "icon.svg")
    with open(svg_path, "w", encoding="utf-8") as fh:
        fh.write(FULL)
    print(f"wrote {os.path.normpath(svg_path)}")

    ico_path = os.path.join(APP_DIR, "favicon.ico")
    sizes = [16, 32, 48, 64, 128, 256]
    base = render_mark(256)
    base.save(ico_path, format="ICO", sizes=[(s, s) for s in sizes])
    print(f"wrote {os.path.normpath(ico_path)}  ({', '.join(str(s) for s in sizes)})")

    apple_path = os.path.join(APP_DIR, "apple-icon.png")
    render_mark(180, background=MIST).convert("RGB").save(apple_path, "PNG")
    print(f"wrote {os.path.normpath(apple_path)}  (180, on {MIST})")


if __name__ == "__main__":
    os.makedirs(OUT_DIR, exist_ok=True)
    ts_dir = os.path.join(os.path.dirname(__file__), "..", "src", "data")
    os.makedirs(ts_dir, exist_ok=True)
    ts_path = os.path.join(ts_dir, "mark-paths.ts")
    with open(ts_path, "w", encoding="utf-8") as fh:
        fh.write(TS)
    print(f"wrote {os.path.normpath(ts_path)}")
    for name, body in [
        ("g-mark.svg", FULL),
        ("g-mark-mono.svg", MONO),
        ("g-mark-outline.svg", OUTLINE),
    ]:
        path = os.path.join(OUT_DIR, name)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(body)
        print(f"wrote {os.path.normpath(path)}  ({len(body)} bytes)")

    build_icons()

    print()
    print(f"  outer radius {R_OUT}  inner {R_IN}  stroke {STROKE}")
    print(f"  orange 45-225   pale 225-270   G 270-360 + crossbar   gap 0-45")
