/**
 * Path data for the Gohil's Group mark.
 *
 * GENERATED by scripts/build-mark.py. Do not edit by hand.
 * Re-run the script if the geometry changes.
 *
 * One ring, centre fitted by least squares off client-assets image 2.
 * Outer radius 90.0, stroke 21.5, on a 200 x 200 viewBox.
 * Orange 45deg to 225deg, pale 225deg to 270deg, the G 270deg to 360deg
 * plus a crossbar on the horizontal diameter, gap 0deg to 45deg.
 */

export const MARK_VIEWBOX = '0 0 200 200'

export const MARK_PATHS = {
  /** Lower left arc. Nearly invisible on a light ground, which is the point. */
  pale: 'M36.36 163.64A90 90 0 0 0 100 190L100 168.5A68.5 68.5 0 0 1 51.563 148.437Z',
  /** The G. Its bowl closes the ring on the right. */
  g: 'M100 89.25L189.356 89.25A90 90 0 0 1 100 190L100 168.5A68.5 68.5 0 0 0 167.651 110.75L100 110.75Z',
  /** The 180 degree orange arc. */
  arc: 'M163.64 36.36A90 90 0 0 0 36.36 163.64L51.563 148.437A68.5 68.5 0 0 1 148.437 51.563Z',
} as const

export const MARK_COLOURS = {
  pale: '#D3D5D7',
  g: '#646668',
  arc: '#E8500C',
} as const
