/**
 * The mark and the GROUP wordmark, as inline SVG.
 *
 * Inline rather than <img> for two reasons: the paths inherit theme colour, so
 * one component serves light, dark and reversed sections; and the load
 * animation needs to reach the individual arcs. DESIGN.md 4.11.
 *
 * Path data is generated by scripts/build-mark.py and scripts/build-lockup.py.
 */

import { MARK_VIEWBOX, MARK_PATHS } from '@/data/mark-paths'
import { GROUP_GLYPHS, GROUP_ADVANCE, GROUP_VIEWBOX } from '@/data/wordmark-paths'
import { COMPANY } from '@/data/company'

interface MarkProps {
  className?: string
  /** Adds the classes the load timeline targets. Home hero only. */
  animated?: boolean
}

export function Mark({ className, animated = false }: MarkProps) {
  return (
    <svg
      viewBox={MARK_VIEWBOX}
      className={className}
      aria-hidden="true"
      focusable="false"
      data-mark={animated ? 'animated' : undefined}
    >
      <path className="mark__pale" d={MARK_PATHS.pale} />
      <path className="mark__g" d={MARK_PATHS.g} />
      <path className="mark__arc" d={MARK_PATHS.arc} />
    </svg>
  )
}

export function GroupWordmark({ className }: { className?: string }) {
  return (
    <svg viewBox={GROUP_VIEWBOX} className={className} aria-hidden="true" focusable="false">
      {GROUP_GLYPHS.map((g, i) => (
        <path
          key={g.char + i}
          d={g.d}
          fill="var(--mark-g)"
          fillRule="evenodd"
          transform={`translate(${i * GROUP_ADVANCE} 0)`}
        />
      ))}
    </svg>
  )
}

/**
 * Horizontal lockup: the mark, then GROUP. This is the reduced lockup the
 * client themselves use, with no "Gohil's". DESIGN.md 4.11.
 */
export function Lockup({
  className,
  markClass = 'h-10 w-10',
  animated = false,
}: {
  className?: string
  markClass?: string
  animated?: boolean
}) {
  return (
    <span className={`inline-flex items-center gap-2.5 ${className ?? ''}`}>
      <Mark className={markClass} animated={animated} />
      <GroupWordmark className="h-[0.72em] w-auto" />
      <span className="sr-only">{COMPANY.group}</span>
    </span>
  )
}
